---
platform: linux
image: docker:///ruby#2.2.4
inputs:
- name: cpt-snake
run:
  path: cpt-snake/ci/tasks/deploy.sh
params:
  CF_IP:                  replace-me
  CF_ENDPOINT:            replace-me
  CF_USERNAME:            replace-me
  CF_PASSWORD:            replace-me
  CF_ORG:                 replace-me
  CF_SPACE:               replace-me
